[boris]
  version = 1

[build.dist]
  command = [["make"]]

[build.branches]
  command = [["make"]]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-submodules]
  command = [["dangling-refs"]]

[build.all-rebased]
  command = [["rebased"]]

